language: python
env:
- TOXENV=py27
- TOXENV=py34
virtualenv:
  system_site_packages: true
install:
- pip install tox coveralls
script:
- tox
after_success:
- "if [ $TOXENV == check ]; then coveralls; fi"
