list:
    container: true
    args:
        - style:
            values: default | unordered | ordered
            default: default
        - data:
            values: $none | $expression
            default: ~
    template: |
        {% set tag = 'ol' if args.style == 'ordered' else 'ul' %}
        <{{tag }}>
            {% if not args.data %}
                {% for item in raw_contents %}
                    <li>{{ item }}</li>
                {% endfor %}
            {% else %}
                <li ng-repeat="{{ args.data }}">{{ contents }}</li>
            {% endif %}
        </{{ tag }}>

h1:
    container: true
    template: | 
        <h1>{{ contents }}</h1>

h2:
    container: true
    template: | 
        <h2>{{ contents }}</h2>

h3:
    container: true
    template: |
        <h3>{{ contents }}</h3>

h4:
    container: true
    template: | 
        <h4>{{ contents }}</h4>

h5:
    container: true
    template: | 
        <h5>{{ contents }}</h5>

h6:
    container: true
    template: | 
        <h6>{{ contents }}</h6>


p:
    container: true
    template: | 
        <p>{{ contents }}</p>

hr:
    container: false
    args:
    template: |
        <hr>
